version: '3.9'

services:
  frontend:
    build: ./frontend
    image: cr.yandex/crpq1hjt5vn1sf4s6j1b/geekbrains-frontend
    ports:
      - 5173:5173
    environment:
      - API_URL=web:8004

  web:
    build: ./backend
    image: cr.yandex/crpq1hjt5vn1sf4s6j1b/geekbrains-backend
    ports:
      - 4000:8000
    command: [ "uvicorn","app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    volumes:
      - ./tmp:/var/planning/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - ML_SERVICE_URL=http://ml-llm:7999
    depends_on:
      - redis
      - db

  prisma-migrate:
    build: ./backend
    image: cr.yandex/crpq1hjt5vn1sf4s6j1b/geekbrains-backend
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    command: >
      sh -c "prisma migrate deploy --schema ./prisma/prisma.schema"
    depends_on:
      - db

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    #    volumes:
    #      - ./cache:/data
    environment:
      REDIS_PORT: 6379

  worker:
    build: ./backend
    image: cr.yandex/crpq1hjt5vn1sf4s6j1b/geekbrains-backend
    command: celery -A app.worker.worker worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - ML_SERVICE_URL=http://ml-llm:7999
    volumes:
            - ${ROOT_DIR}tmp:/var/planning/uploads
    depends_on:
      - redis
      - db

  flower:
    build: ./backend
    image: cr.yandex/crpq1hjt5vn1sf4s6j1b/geekbrains-backend
    ports:
      - 5555:5555
    command: celery -A app.worker.worker flower --loglevel=info
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db

  db:
    container_name: db-local
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always

  ml-llm:
    image: cr.yandex/crpq1hjt5vn1sf4s6j1b/geekbrains-ml
    build:
      context: ./ml/
    command: [ "uvicorn","app.main:app", "--host", "0.0.0.0", "--port", "7999", "--reload" ]
    environment:
      LLAMA_MODEL_PATH: "/app/models/Meta-Llama-3-8B-Instruct-Q4_K_M.gguf"
    volumes:
      - ${ROOT_DIR}app:/root/.cache
      - ${ROOT_DIR}app/models:/app/models
    ports:
      - 8002:7999

