name: Backend Python CI workflow
on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'backend/**'
jobs:
  deploy-container:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - run: echo $YANDEX_AUTH_KEY | docker login --username json_key --password-stdin cr.yandex
        env:
          YANDEX_AUTH_KEY: ${{ secrets.YANDEX_AUTH_KEY }}
      - run: |
          echo "Packaging docker image ..."
          tag="$DOCKER_REGISTRY/geekbrains-backend:${{ github.sha }}"
          docker build -t $tag .
          docker push $tag
        env:
          DOCKER_REGISTRY: cr.yandex/crpq1hjt5vn1sf4s6j1b