name: Frontend CI workflow
on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18.x
          cache-dependency-path: ./frontend/package-lock.json
      - run: npm ci
      - run: npm run build
        env:
          VITE_API_URL: https://geekbrains.banzai-predict.site

      - run: zip -qq -r build.zip dist

      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          path: ./frontend/build.zip
          name: build.zip

  build-container:
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - run: echo $YANDEX_AUTH_KEY | docker login --username json_key --password-stdin cr.yandex
        env:
          YANDEX_AUTH_KEY: ${{ secrets.YANDEX_AUTH_KEY }}
      - run: |
          echo "Packaging docker image ..."
          tag="$DOCKER_REGISTRY/level-frontend:${{ github.sha }}"
          docker build -t $tag .
          docker push $tag
        env:
          DOCKER_REGISTRY: cr.yandex/crp6hfvvdlm0ddass92t

